name: Action Sample

on:
  push:
    branches:
      - master
      - working
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from repository
        uses: actions/checkout@v2

      - name: Setting up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pydssp
        run: python setup.py install
      
      - name: Test
        run: python tests/test.py
